<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Compliance\Resources\default-rules.json" />
    <EmbeddedResource Include="Lifecycle\Resources\os-eol.json" />
    <EmbeddedResource Include="Hardware\Resources\hardware-specs.json" />
  </ItemGroup>

</Project>
